### ISSUE TITLE
In the Javascript interpreter, 1/0 does not return Infinity

### ISSUE THREAD

**Issue by Lucas-C** [viebel/klipse#122] opened 2016-10-02 14:15 UTC
I used a very basic setup, and tested with Chrome:

``` html
<div class="klipse">
1/0
</div>
<link rel="stylesheet" type="text/css" href="http://app.klipse.tech/css/codemirror.css">
<script>
window.klipse_settings = {selector_eval_js: '.klipse'};
</script>
<script src="http://app.klipse.tech/plugin/js/klipse_plugin.min.js"></script>
```

**Comment by viebel** [comment] 2016-10-02 14:49
Nice catch!

Did you other inconsistencies?

**Comment by viebel** [comment] 2016-11-07 10:03
@Lucas-C the root cause is that `Infinity` is [not part of JSON](http://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript) and currently KLIPSE uses JSON.stringify to stringify the result of `eval`.

I found a library that pretty print javascript without using JSON.stringify:
https://github.com/cvadillo/js-object-pretty-print
It will solve the issue

**Comment by Lucas-C** [comment] 2016-11-07 14:36
Thank you !

**Comment by viebel** [comment] 2016-12-06 11:28
This issue is going to be fixed by #149 
By the way the same problem occured with ES6 Symbols

**Comment by viebel** [comment] 2017-01-18 05:53
It is fixed! Can you please double check @Lucas-C ?

**Closed by viebel** 2017-01-18 05:53 UTC

**Comment by Lucas-C** [comment] 2017-01-18 21:57
The original bug seems fixed, but now there is a `"klipse-container-0"` string by default in the 2nd `.CodeMirror` block :

![screenshot from 2017-01-18 22-54-48](https://cloud.githubusercontent.com/assets/925560/22084690/5f10b46c-ddd1-11e6-9c05-922ff232c594.png)

**Comment by Lucas-C** [comment] 2017-01-18 21:57
Any idea on where that is coming from ??

**Comment by viebel** [comment] 2017-01-19 03:27
Yeah. It's the id of the container associated with the the snippet. Try to type 
```clojure
(set!
 (.-innerHTML (js/document.getElementById "klipse-container-0")) 
 "<div style='color:blue;'> Hello <b>World</b>!</div>")
```

**Comment by Lucas-C** [comment] 2017-01-20 09:55
I could not make it work properly:
- `data-async-code` simply broke the code evaluation
- there is and HTML element with ID "klipse-container-0" but it is not the one that contains the text I see

Hence I decided to revert using v0.7.0 : https://lucas-c.github.io/progWorkshop-bootstrapPage/workshop_material/challenges/3.html

**Comment by viebel** [comment] 2017-01-20 13:47
I see. Indeed it's a bug inside KLIPSE.
Could you open a separate issue please?
(Très sympa ton site!!!)

**Comment by viebel** [comment] 2017-01-22 04:31
solved in latest release....

**Comment by Lucas-C** [comment] 2017-01-24 06:29
Thanks
(merci!)
